package esunbank.com.tw.it18;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class form implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Position(3)
	private java.lang.String complete;

    @org.kie.api.definition.type.Position(1)
	private java.lang.String reject;

    @org.kie.api.definition.type.Position(2)
	private java.lang.String send;

    @org.kie.api.definition.type.Position(0)
	private java.lang.String stage1;

    @org.kie.api.definition.type.Position(4)
	private java.lang.String reply;

	@org.kie.api.definition.type.Position(5)
	private java.lang.String isthesame;

	@org.kie.api.definition.type.Position(6)
	private java.lang.String stage2;

	@org.kie.api.definition.type.Position(value = 7)
	private java.lang.String change;

	public java.lang.String getComplete() {
        return this.complete;
    }
    
    public void setComplete(java.lang.String complete) {
        this.complete = complete;
    }

    public java.lang.String getReject() {
        return this.reject;
    }
    
    public void setReject(java.lang.String reject) {
        this.reject = reject;
    }

    public java.lang.String getSend() {
        return this.send;
    }
    
    public void setSend(java.lang.String send) {
        this.send = send;
    }

    public java.lang.String getStage1() {
        return this.stage1;
    }
    
    public void setStage1(java.lang.String stage1) {
        this.stage1 = stage1;
    }

	public java.lang.String getReply() {
		return this.reply;
	}

	public void setReply(java.lang.String reply) {
		this.reply = reply;
	}

	public java.lang.String getIsthesame() {
		return this.isthesame;
	}

	public void setIsthesame(java.lang.String isthesame) {
		this.isthesame = isthesame;
	}

	public java.lang.String getStage2() {
		return this.stage2;
	}

	public void setStage2(java.lang.String stage2) {
		this.stage2 = stage2;
	}

	public java.lang.String getChange() {
		return this.change;
	}

	public void setChange(java.lang.String change) {
		this.change = change;
	}

	public form() {
	}

	public form(java.lang.String stage1, java.lang.String reject,
			java.lang.String send, java.lang.String complete,
			java.lang.String reply, java.lang.String isthesame,
			java.lang.String stage2, java.lang.String change) {
		this.stage1 = stage1;
		this.reject = reject;
		this.send = send;
		this.complete = complete;
		this.reply = reply;
		this.isthesame = isthesame;
		this.stage2 = stage2;
		this.change = change;
	}

}