package it02.it02;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "form")
public class form implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public form() {
    }

}