package it02.it02;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("form")
public class form implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Position(0)
	private java.lang.String stage1;
	@org.kie.api.definition.type.Position(1)
	private java.lang.String stage2;

	@org.kie.api.definition.type.Position(2)
	private java.lang.String stage3;

	@org.kie.api.definition.type.Position(3)
	private java.lang.String stage4;

	@org.kie.api.definition.type.Position(4)
	private java.lang.String stage5;

	@org.kie.api.definition.type.Position(5)
	private java.lang.String stage6;

	@org.kie.api.definition.type.Position(6)
	private java.lang.String stage7;

	@org.kie.api.definition.type.Position(value = 7)
	private java.lang.String send;

	@org.kie.api.definition.type.Position(value = 8)
	private java.lang.String reject;

	public java.lang.String getStage1() {
		return this.stage1;
	}

	public void setStage1(java.lang.String stage1) {
		this.stage1 = stage1;
	}

	public java.lang.String getStage2() {
		return this.stage2;
	}

	public void setStage2(java.lang.String stage2) {
		this.stage2 = stage2;
	}

	public java.lang.String getStage3() {
		return this.stage3;
	}

	public void setStage3(java.lang.String stage3) {
		this.stage3 = stage3;
	}

	public java.lang.String getStage4() {
		return this.stage4;
	}

	public void setStage4(java.lang.String stage4) {
		this.stage4 = stage4;
	}

	public java.lang.String getStage5() {
		return this.stage5;
	}

	public void setStage5(java.lang.String stage5) {
		this.stage5 = stage5;
	}

	public java.lang.String getStage6() {
		return this.stage6;
	}

	public void setStage6(java.lang.String stage6) {
		this.stage6 = stage6;
	}

	public java.lang.String getStage7() {
		return this.stage7;
	}

	public void setStage7(java.lang.String stage7) {
		this.stage7 = stage7;
	}

	public java.lang.String getSend() {
		return this.send;
	}

	public void setSend(java.lang.String send) {
		this.send = send;
	}

	public java.lang.String getReject() {
		return this.reject;
	}

	public void setReject(java.lang.String reject) {
		this.reject = reject;
	}

	public form() {
	}

	public form(java.lang.String stage1, java.lang.String stage2,
			java.lang.String stage3, java.lang.String stage4,
			java.lang.String stage5, java.lang.String stage6,
			java.lang.String stage7, java.lang.String send,
			java.lang.String reject) {
		this.stage1 = stage1;
		this.stage2 = stage2;
		this.stage3 = stage3;
		this.stage4 = stage4;
		this.stage5 = stage5;
		this.stage6 = stage6;
		this.stage7 = stage7;
		this.send = send;
		this.reject = reject;
	}

}