package esunbank.com.tw.it03;

======================
import java.util.ArrayList;
import java.util.List;

import org.json.JSONArray;
import org.json.JSONObject;

import esunbank.com.tw.it03.form;


/**
 * This class was automatically generated by the data modeler tool.
 */

public class FormTransfer implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public FormTransfer() {
    }

public static it03Form formTransfer(String parameter ) throws Exception {
		

			form startform =new form();
			JSONObject json  = new JSONObject(parameter);
			
			startform.setIsBUSetting(json.getString("isBUSetting"));
			startform.setSend(json.getString("send"));
			startform.setCancel(json.getString("cancel"));
			startform.setReject(json.getString("reject"));
			startform.setJump(json.getString("jump"));
			startform.setStationFour(json.getString("stationFour"));
			startform.setStationSix(json.getString("stationSix"));
			startform.setCdept(json.getString("cdept"));
			startform.setAssignOrgPicker(json.getString("assignOrgPicker"));
			startform.setCancelCompleted(json.getString("cancelCompleted"));
			startform.setStage2(json.getString("stage2"));
			startform.setStage3(json.getString("stage3"));
			startform.setStage4(json.getString("stage4"));
			startform.setStage5(json.getString("stage5"));
			startform.setStage6(json.getString("stage6"));
			startform.setStage7(json.getString("stage7"));
			startform.setApplicant(json.getString("applicant"));

			
			
			
			
			
//			startform.setFirstStage(json.getString("firstStage"));

//////-------------------------
			
			 JSONArray jsonArray = json.getJSONArray("stage");
	    
			 JSONObject tempCSlist  = new JSONObject(parameter);
			  List<counterSignList> result = new ArrayList<counterSignList>();


	            for (int i = 0; i < jsonArray.length(); i++) {
	    
	            	counterSignList stageTemp = new counterSignList();
//	                 stageTemp.setSigner(jsonArray.getString(i)) ;
	            	tempCSlist=new JSONObject(jsonArray.getString(i));
	                 stageTemp.setStage8(tempCSlist.getString("stage8"));
	           
//	                 System.out.println(stageTemp.getSigner());
	                 
	                 result.add(stageTemp);
	
	               
	            }
	            
	            startform.setCSList(result);  
	           
		
			return startform;
			
//////////--------		
			

	}
}


===================

public class formTransfer implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public formTransfer() {
    }

}