package esunbank.com.tw.it03;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class formTransfer implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public formTransfer() {
    }

}