package esunbank.com.tw.it03;

import java.util.ArrayList;

import java.util.List;

import org.json.JSONArray;
import org.json.JSONObject;

import esunbank.com.tw.it03.form;
import esunbank.com.tw.it03.stage;
import esunbank.com.tw.it03.stage1;
import esunbank.com.tw.it03.stage2;
import esunbank.com.tw.it03.stage3;
import esunbank.com.tw.it03.stage4;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FormTransfer implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public FormTransfer() {
    }

public static form formTransfer(String parameter ) throws Exception {
		

			form startform =new form();
			JSONObject json  = new JSONObject(parameter);
			
			startform.setAssign(json.getString("assign"));
			startform.setChange(json.getString("change"));
			startform.setComplete(json.getString("complete"));
			startform.setHostsr(json.getString("send"));
			startform.setIscitrix(json.getString("iscitrix"));
			startform.setIsgeneral(json.getString("assignOrgPicker"));
			startform.setIsmgr(json.getString("ismgr"));
			startform.setIsthesame(json.getString("cancelCompleted"));

			startform.setOthermgr(json.getString("send"));
			startform.setReject(json.getString("reject"));
			startform.setReply(json.getString("cdept"));
			startform.setSend(json.getString("send"));
			
			startform.setStage1(json.getString("stage1"));
			startform.setStage2(json.getString("stage2"));
			startform.setStage3(json.getString("stage3"));
			startform.setStage4(json.getString("stage4"));
			startform.setStage5(json.getString("stage5"));
			startform.setStage6(json.getString("stage6"));
			startform.setStage7(json.getString("stage7"));
			startform.setStage8(json.getString("stage8"));
			startform.setStage9(json.getString("stage9"));
			startform.setStage10(json.getString("stage10"));
			startform.setStage11(json.getString("stage11"));	
			
			startform.setStage13(json.getString("stage13"));
			startform.setStage14(json.getString("stage14"));
//			startform.setFirstStage(json.getString("firstStage"));

//////-------------------------
			
			 JSONArray jsonArray = json.getJSONArray("stage1list");
	    
			 JSONObject tempCSlist  = new JSONObject(parameter);
			  List<stage1> result = new ArrayList<stage1>();


	            for (int i = 0; i < jsonArray.length(); i++) {
	    
	            	stage1 stageTemp = new stage1();
//	                 stageTemp.setSigner(jsonArray.getString(i)) ;
	            	tempCSlist=new JSONObject(jsonArray.getString(i));
	                 stageTemp.User(tempCSlist.getString("user"));
	           
//	                 System.out.println(stageTemp.getSigner());
	                 
	                 result.add(stageTemp);
	
	               
	            }
	            
	            startform.setStage1list(result);  
	           
		
			return startform;
			
//////////--------		
			

	}
}


