package esunbank.com.tw.it03;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class stage4 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String stage4;

    public stage4() {
    }
    
    public stage4(java.lang.String stage4) {
        this.stage4 = stage4;
    }

    public java.lang.String getStage4() {
        return this.stage4;
    }
    
    public void setStage4(java.lang.String stage4) {
        this.stage4 = stage4;
    }

}