package esunbank.com.tw.it03;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class stage2 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String stage2;

    public stage2() {
    }
    
    public stage2(java.lang.String stage2) {
        this.stage2 = stage2;
    }

    public java.lang.String getStage2() {
        return this.stage2;
    }
    
    public void setStage2(java.lang.String stage2) {
        this.stage2 = stage2;
    }

}