package esunbank.com.tw.it03;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class stage implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String stage;

    public stage() {
    }
    
    public stage(java.lang.String stage) {
        this.stage = stage;
    }

    public java.lang.String getStage() {
        return this.stage;
    }
    
    public void setStage(java.lang.String stage) {
        this.stage = stage;
    }

}