package esunbank.com.tw.it03;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class stage3 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String stage3;

    public stage3() {
    }
    
    public stage3(java.lang.String stage3) {
        this.stage3 = stage3;
    }

    public java.lang.String getStage3() {
        return this.stage3;
    }
    
    public void setStage3(java.lang.String stage3) {
        this.stage3 = stage3;
    }

}