package esunbank.com.tw.it03;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class stage1 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Position(value = 0)
	private java.lang.String user;

	public java.lang.String getUser() {
		return this.user;
	}

	public void setUser(java.lang.String user) {
		this.user = user;
	}

	public stage1() {
	}

	public stage1(java.lang.String user) {
		this.user = user;
	}

}