package esunbank.com.tw.it02;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class form implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String stage1;

    public form() {
    }
    
    public form(java.lang.String stage1) {
        this.stage1 = stage1;
    }

    public java.lang.String getStage1() {
        return this.stage1;
    }
    
    public void setStage1(java.lang.String stage1) {
        this.stage1 = stage1;
    }

}