package esunbank.com.tw.it12;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class form implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Position(value = 0)
	private java.lang.String stage1;
	@org.kie.api.definition.type.Position(value = 1)
	private java.lang.String stage2;
	@org.kie.api.definition.type.Position(value = 2)
	private java.lang.String send;
	@org.kie.api.definition.type.Position(value = 3)
	private java.lang.String reject;

	public java.lang.String getStage1() {
		return this.stage1;
	}

	public void setStage1(java.lang.String stage1) {
		this.stage1 = stage1;
	}

	public java.lang.String getStage2() {
		return this.stage2;
	}

	public void setStage2(java.lang.String stage2) {
		this.stage2 = stage2;
	}

	public java.lang.String getSend() {
		return this.send;
	}

	public void setSend(java.lang.String send) {
		this.send = send;
	}

	public java.lang.String getReject() {
		return this.reject;
	}

	public void setReject(java.lang.String reject) {
		this.reject = reject;
	}

	public form() {
	}

	public form(java.lang.String stage1, java.lang.String stage2,
			java.lang.String send, java.lang.String reject) {
		this.stage1 = stage1;
		this.stage2 = stage2;
		this.send = send;
		this.reject = reject;
	}

}